### ISSUE TITLE
Improvement suggestion

### ISSUE THREAD

**Issue by dongivan** [eagleoflqj/sympy_beta#5]
## Input
`Integral(1/(e**(x**2/2)*(sqrt(2*pi))), (x, -oo, oo))`
## How can it be better?

The expression (defined integral of standard normal distribution from negative infinity to position infinity) should equal 1(and it does in WolframAlpha), however the answer is another expression with \int^{\infty}_{-\infty}e^{-\frac{x^2}{2}}dx. Is it a bug or a feature of sympy?

**Comment by eagleoflqj** [comment]
For SymPy this is not a bug, as it has `E` as base of natural log and exponential function is `exp(x)`.
However as a user app, SymPy Beta can do more about it. It doesn't necessarily follow all SymPy conventions. It should be smart about what `e` is without extra instruction from user.

Below is what I'm going to implement:
* If the expression contains variable `a,b,c,d`, then treat `e` as a variable
* Otherwise, treat `e` as base of natural log.

This is subject to change if another reasonable complaint occurs.

**Comment by eagleoflqj** [comment]
Fixed at 202db2db1b34467e3ccf6fa1720796284f0a7d54

**Comment by dongivan** [comment]
Thx for the reply!
There is one more bug (or feature):
It seems that `SymPy Beta` treat `d` as a differentiation symbol in `\int^1_0 dx` but as a variable in `\int^1_0 d{x}`: it transfroms the former to `integrate(1,(x,0,1))` and the latter to `integrate(d*x,(x,0,1))`.

I'm a complete beginner to LaTeX. Is there a convention or rule that the symbols after the differentiation symbol should not be wrapped in `{}`?

**Comment by eagleoflqj** [comment]
SymPy Beta directly inherits SymPy's LaTex parser.
```py
>>> from sympy.parsing.latex import parse_latex
>>> parse_latex(R'\int xd{x}')
Integral(x*(d*x), x)
```
So this is an issue of SymPy, which is relevant to https://github.com/sympy/sympy/issues/23551
I'm not aware of how common `d{x}` is used. It renders the same as `dx` but requires more characters. If it's common, it should be addressed in SymPy.

**Comment by dongivan** [comment]
Thank you!
